# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/mihalixz/FileManageC/FileManageCpp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/mihalixz/FileManageC/FileManageCpp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mihalixz/FileManageC/FileManageCpp/CMakeFiles /home/mihalixz/FileManageC/FileManageCpp//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mihalixz/FileManageC/FileManageCpp/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named FileManageC

# Build rule for target.
FileManageC: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 FileManageC
.PHONY : FileManageC

# fast build rule for target.
FileManageC/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FileManageC.dir/build.make CMakeFiles/FileManageC.dir/build
.PHONY : FileManageC/fast

file/copy/file_copy_bin.o: file/copy/file_copy_bin.c.o
.PHONY : file/copy/file_copy_bin.o

# target to build an object file
file/copy/file_copy_bin.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FileManageC.dir/build.make CMakeFiles/FileManageC.dir/file/copy/file_copy_bin.c.o
.PHONY : file/copy/file_copy_bin.c.o

file/copy/file_copy_bin.i: file/copy/file_copy_bin.c.i
.PHONY : file/copy/file_copy_bin.i

# target to preprocess a source file
file/copy/file_copy_bin.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FileManageC.dir/build.make CMakeFiles/FileManageC.dir/file/copy/file_copy_bin.c.i
.PHONY : file/copy/file_copy_bin.c.i

file/copy/file_copy_bin.s: file/copy/file_copy_bin.c.s
.PHONY : file/copy/file_copy_bin.s

# target to generate assembly for a file
file/copy/file_copy_bin.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FileManageC.dir/build.make CMakeFiles/FileManageC.dir/file/copy/file_copy_bin.c.s
.PHONY : file/copy/file_copy_bin.c.s

file/copy/file_copy_txt.o: file/copy/file_copy_txt.c.o
.PHONY : file/copy/file_copy_txt.o

# target to build an object file
file/copy/file_copy_txt.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FileManageC.dir/build.make CMakeFiles/FileManageC.dir/file/copy/file_copy_txt.c.o
.PHONY : file/copy/file_copy_txt.c.o

file/copy/file_copy_txt.i: file/copy/file_copy_txt.c.i
.PHONY : file/copy/file_copy_txt.i

# target to preprocess a source file
file/copy/file_copy_txt.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FileManageC.dir/build.make CMakeFiles/FileManageC.dir/file/copy/file_copy_txt.c.i
.PHONY : file/copy/file_copy_txt.c.i

file/copy/file_copy_txt.s: file/copy/file_copy_txt.c.s
.PHONY : file/copy/file_copy_txt.s

# target to generate assembly for a file
file/copy/file_copy_txt.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FileManageC.dir/build.make CMakeFiles/FileManageC.dir/file/copy/file_copy_txt.c.s
.PHONY : file/copy/file_copy_txt.c.s

file/name/file_exten.o: file/name/file_exten.c.o
.PHONY : file/name/file_exten.o

# target to build an object file
file/name/file_exten.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FileManageC.dir/build.make CMakeFiles/FileManageC.dir/file/name/file_exten.c.o
.PHONY : file/name/file_exten.c.o

file/name/file_exten.i: file/name/file_exten.c.i
.PHONY : file/name/file_exten.i

# target to preprocess a source file
file/name/file_exten.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FileManageC.dir/build.make CMakeFiles/FileManageC.dir/file/name/file_exten.c.i
.PHONY : file/name/file_exten.c.i

file/name/file_exten.s: file/name/file_exten.c.s
.PHONY : file/name/file_exten.s

# target to generate assembly for a file
file/name/file_exten.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FileManageC.dir/build.make CMakeFiles/FileManageC.dir/file/name/file_exten.c.s
.PHONY : file/name/file_exten.c.s

file/rbin/bin_converter.o: file/rbin/bin_converter.c.o
.PHONY : file/rbin/bin_converter.o

# target to build an object file
file/rbin/bin_converter.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FileManageC.dir/build.make CMakeFiles/FileManageC.dir/file/rbin/bin_converter.c.o
.PHONY : file/rbin/bin_converter.c.o

file/rbin/bin_converter.i: file/rbin/bin_converter.c.i
.PHONY : file/rbin/bin_converter.i

# target to preprocess a source file
file/rbin/bin_converter.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FileManageC.dir/build.make CMakeFiles/FileManageC.dir/file/rbin/bin_converter.c.i
.PHONY : file/rbin/bin_converter.c.i

file/rbin/bin_converter.s: file/rbin/bin_converter.c.s
.PHONY : file/rbin/bin_converter.s

# target to generate assembly for a file
file/rbin/bin_converter.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FileManageC.dir/build.make CMakeFiles/FileManageC.dir/file/rbin/bin_converter.c.s
.PHONY : file/rbin/bin_converter.c.s

flags/flags_analys.o: flags/flags_analys.c.o
.PHONY : flags/flags_analys.o

# target to build an object file
flags/flags_analys.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FileManageC.dir/build.make CMakeFiles/FileManageC.dir/flags/flags_analys.c.o
.PHONY : flags/flags_analys.c.o

flags/flags_analys.i: flags/flags_analys.c.i
.PHONY : flags/flags_analys.i

# target to preprocess a source file
flags/flags_analys.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FileManageC.dir/build.make CMakeFiles/FileManageC.dir/flags/flags_analys.c.i
.PHONY : flags/flags_analys.c.i

flags/flags_analys.s: flags/flags_analys.c.s
.PHONY : flags/flags_analys.s

# target to generate assembly for a file
flags/flags_analys.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FileManageC.dir/build.make CMakeFiles/FileManageC.dir/flags/flags_analys.c.s
.PHONY : flags/flags_analys.c.s

main.o: main.c.o
.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FileManageC.dir/build.make CMakeFiles/FileManageC.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i
.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FileManageC.dir/build.make CMakeFiles/FileManageC.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s
.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FileManageC.dir/build.make CMakeFiles/FileManageC.dir/main.c.s
.PHONY : main.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... FileManageC"
	@echo "... file/copy/file_copy_bin.o"
	@echo "... file/copy/file_copy_bin.i"
	@echo "... file/copy/file_copy_bin.s"
	@echo "... file/copy/file_copy_txt.o"
	@echo "... file/copy/file_copy_txt.i"
	@echo "... file/copy/file_copy_txt.s"
	@echo "... file/name/file_exten.o"
	@echo "... file/name/file_exten.i"
	@echo "... file/name/file_exten.s"
	@echo "... file/rbin/bin_converter.o"
	@echo "... file/rbin/bin_converter.i"
	@echo "... file/rbin/bin_converter.s"
	@echo "... flags/flags_analys.o"
	@echo "... flags/flags_analys.i"
	@echo "... flags/flags_analys.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

